config/routes.rb
NewVend::Application.routes.draw do
  get "machines/new"
  get 'request_tasks/count' => 'request_tasks#count'
  get 'requests/count' => 'requests#count'
  get 'mobile' => 'application#mobile', :as => :mobile

  resources :machines, only: [:index, :show, :create, :new]
  resources :users, only: [:show, :edit, :update, :new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :requests, only: [:index, :destroy, :create, :update, :edit, :show]
  resources :messages, only: [:index, :destroy, :create, :update, :edit]
  resources :request_tasks, only: [:index, :edit, :update, :show]
  resources :tasks, only: [:index, :create, :destroy, :update]
  resources :employees, only: [:index, :create, :destroy, :edit, :update]
  resources :message_tasks, only: [:index]
  resources :attributes, only: [:index, :create, :destroy, :update]
  resources :request_types, only: [:index, :create, :destroy, :update, :show]
  resources :new_vend_settings, only: [:index, :show, :update]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get 'to_assign_count' => 'request_tasks#to_assign_count', :as => :to_assign_count
  get 'to_audit_count' => 'request_tasks#to_audit_count', :as => :to_audit_count
  get 'to_execute_count' => 'request_tasks#to_execute_count', :as => :to_execute_count
  get 'to_read_assign_count' => 'request_tasks#to_read_assign_count', :as => :to_read_assign_count
  get 'to_read_execute_count' => 'request_tasks#to_read_execute_count', :as => :to_read_execute_count
  get 'to_read_by_executor_count' => 'request_tasks#to_read_by_executor_count', :as => :to_read_by_executor_count
  get 'to_read_by_assigner_count' => 'request_tasks#to_read_by_assigner_count', :as => :to_read_by_assigner_count
  get 'to_read_by_auditor_count' => 'request_tasks#to_read_by_auditor_count', :as => :to_read_by_auditor_count
  get 'to_read_by_employee_count' => 'request_tasks#to_read_by_employee_count', :as => :to_read_by_employee_count
  get 'read_request_task' => 'request_tasks#read', :as => :read_request_task
  get 'current_employee' => 'employees#current_employee', :as => :current_employee

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :signed_in_user

  def home
  end

  def help
  end

  def signed_in_user
    redirect_to signin_url, notice: "Пожалуйста, войдите в систему" unless signed_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<script type="text/javascript">
	$(document).ready(function() {
		$('li#help-page').addClass('active');
	});
</script>

<div class="content">
	Help 
	<p>Find me in app/views/static_pages/help.html.erb</p>
</div>

app/views/static_pages/home.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$('li#home-page').addClass('active');
	});
</script>

<div class="content">
	<!--<% if !signed_in? %>
		<%= link_to "Войти в систему", signin_path %>
	<% end %>-->
	<h1>Меню</h1><hr>
	<ul class="nav nav-pills">
	<li><%= link_to "Заявки", requests_path %></li>
	<li><%= link_to "Поручения", request_tasks_path %></li>
	</ul>
	<hr>
	<ul class="nav nav-pills">
	<li><%= link_to "Автоматы", machines_path %></li>
	<li><%= link_to "Типы сигналов", messages_path %></li>
	<li><%= link_to "Типы поручений", tasks_path %></li>
	</ul>
</div>