config/routes.rb
NewVend::Application.routes.draw do
  get "machines/new"
  get 'request_tasks/count' => 'request_tasks#count'
  get 'requests/count' => 'requests#count'
  get 'mobile' => 'application#mobile', :as => :mobile

  resources :machines, only: [:index, :show, :create, :new]
  resources :users, only: [:show, :edit, :update, :new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :requests, only: [:index, :destroy, :create, :update, :edit, :show]
  resources :messages, only: [:index, :destroy, :create, :update, :edit]
  resources :request_tasks, only: [:index, :edit, :update, :show]
  resources :tasks, only: [:index, :create, :destroy, :update]
  resources :employees, only: [:index, :create, :destroy, :edit, :update]
  resources :message_tasks, only: [:index]
  resources :attributes, only: [:index, :create, :destroy, :update]
  resources :request_types, only: [:index, :create, :destroy, :update, :show]
  resources :new_vend_settings, only: [:index, :show, :update]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get 'to_assign_count' => 'request_tasks#to_assign_count', :as => :to_assign_count
  get 'to_audit_count' => 'request_tasks#to_audit_count', :as => :to_audit_count
  get 'to_execute_count' => 'request_tasks#to_execute_count', :as => :to_execute_count
  get 'to_read_assign_count' => 'request_tasks#to_read_assign_count', :as => :to_read_assign_count
  get 'to_read_execute_count' => 'request_tasks#to_read_execute_count', :as => :to_read_execute_count
  get 'to_read_by_executor_count' => 'request_tasks#to_read_by_executor_count', :as => :to_read_by_executor_count
  get 'to_read_by_assigner_count' => 'request_tasks#to_read_by_assigner_count', :as => :to_read_by_assigner_count
  get 'to_read_by_auditor_count' => 'request_tasks#to_read_by_auditor_count', :as => :to_read_by_auditor_count
  get 'to_read_by_employee_count' => 'request_tasks#to_read_by_employee_count', :as => :to_read_by_employee_count
  get 'read_request_task' => 'request_tasks#read', :as => :read_request_task
  get 'current_employee' => 'employees#current_employee', :as => :current_employee

end

app/models/user.rb
class User < ActiveRecord::Base
	include ActiveModel::Dirty

	validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
	validates :password_digest, presence: true

	belongs_to :employee

	before_create :create_remember_token

	has_secure_password

	validates_inclusion_of :menu_position, :in => [:hidden, :shown]

	MENU_POSITIONS = {
		:hidden => "Скрыта",
		:shown => "Показана"
	}

	def menu_position
    	read_attribute(:menu_position).to_sym
    end

    def menu_position= (value)
    	write_attribute(:menu_position, value.to_s)
    end

    def self.menu_positions
    	MENU_POSITIONS
    end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]
	before_action :signed_in_user, only: [:show, :edit, :update]

	respond_to :html, :json

	def show
	end

	def index
		@users = User.all
		@ng_controller = "Users"

		respond_with @users.collect { |u| u.attributes.merge!({ :employee => u.employee }) }
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(new_user_params)

		respond_to do |format|
		    if @user.save
		    	format.html { redirect_to @user, notice: 'User was successfully created.' }
		        format.js   {}
		        format.json { render json: @user, status: :created, location: @user }
		    else
		    	format.html { render action: 'new' }
		        format.js   {}
		        format.json { render json: @user.errors, status: :unprocessable_entity }
		    end
		end
	end

	def update
		respond_to do |format|
		  if @user.update(user_params)
		    format.html { redirect_to @user, notice: 'User was successfully updated.' }
		    format.json { render json: @user.attributes.merge!({ :employee => @user.employee }), status: :created, location: @user }
		  else
		    format.html { render action: 'edit' }
		    format.json { render json: @user.errors, status: :unprocessable_entity }
		  end
		end
	end

	def signed_in_user
	  redirect_to signin_url, notice: "Пожалуйста, войдите в систему" unless signed_in?
	end

	private
		def set_user
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(:employee_id, :menu_position)
		end

		def new_user_params
			params.require(:user).permit(:name, :password, :password_confirmation)
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_all.html.erb
<h1>Пользователи</h1>

<div fixedheader class="standart-table-container" ng-show="!editing">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Номер</th>
        <th>Логин</th>
        <th>Полное имя</th>
      </tr>
      <tr>
        <td><input ng-model="search.id" class="form-control input-sm" ng-change="changeWidth()"></td>
        <td><input ng-model="search.name" class="form-control input-sm" ng-change="changeWidth()"></td>
        <td></td>
      </tr>
    </thead>

    <tbody>
      <tr ng-repeat="user in users | filter:search">
        <td ng-click="clickUser($index)">{{user.id}}</td>
        <td ng-click="clickUser($index)">{{user.name}}</td>
        <td ng-click="clickUser($index)">{{user.employee.name}}</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/_form_edit.html.erb
<div ng-show="editing" class="border-top">
<button type="button" class="close" ng-click="editing=false">&times;</button>
  <h1 class="text-center">Пользователь {{editingId}}</h1>
  <form ng-submit="updateUser()" class="form-horizontal">
    <div class="form-group"
      ng-class='{"has-warning": !editingInputs.employee_id, "has-success": editingInputs.employee_id}'>
      <label class="col-sm-2 control-label" for="employee_id">Сотрудник</label>
      <div class="col-sm-8">
      <%= select_tag :employee_id, options_for_select([["", nil]] + Employee.all.collect { |e| [e.name, e.id] }), :class => "form-control", 'ng-model' => 'editingEmployeeId' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <input type="submit" value="Сохранить" class="btn btn-primary">
        <button type="button" class="btn btn-primary" ng-click="editing=false">Отмена</button>
      </div>
    </div>
  </form>
</div>

app/views/users/_form_new.html.erb
<%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>
	<h1 class="text-center">Новый пользователь</h1><br>
    <div id="name" class="form-group">
      <%= f.label :name, "Имя", :class => "col-sm-4 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
    <div id="password" class="form-group">
      <%= f.label :password, "Пароль", :class => "col-sm-4 control-label" %>
      <div class="col-sm-6">
        <%= f.password_field :password, :class => "form-control" %>
      </div>
    </div>
    <div id="password_confirmation" class="form-group">
      <%= f.label :password_confirmation, "Подтверждение пароля", :class => "col-sm-4 control-label" %>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>
    </div>

    <div class="text-center"><%= f.submit "Подтвердить", class: "btn btn-primary" %></div>
<% end %> 

app/views/users/create.js.erb
<% if @user.errors.count != 0 %>
	var errors = <%= raw @user.errors.to_json %>;

	for(var key in errors) {
		if(errors[key].length > 0) {
			$('#newUser').find('#' + key).addClass('has-error');
		}
	}

	var msg = $("#error-msg");
	showErrorMessage("Количество ошибок: <%= @user.errors.count %><br>" +
	                 "Проверьте обязательные для ввода поля",
	                 msg);
<% else %>
	
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.name) %>

<script type="text/javascript">
	$(document).ready(function() {
		$('#user-page').addClass('active');
	});
</script>

<div class="content">
	<div id="success-msg"></div>
	<div id="user">
		<div class="row" id="edit-label">
		    <div class="col-md-10 text-center"><h1>Пользователь <%= @user.id %></h1></div>
		</div>

		<%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>
		    <div class="form-group">
		      <%= f.label :employee_id, "Сотрудник", :class => "col-sm-2 control-label" %>
		      <div class="col-sm-10">
		        <%= f.select :employee_id, options_for_select([["", nil]] + Employee.all.collect { |e| [e.name, e.id] }, :selected => @user.employee ? @user.employee_id : nil), {}, {:class => "form-control"} %>
		      </div>
		    </div>

		    <div class="text-center"><%= f.submit "Подтвердить", class: "btn btn-primary" %></div>
		<% end %> 
	</div>
</div>

app/views/users/index.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$('li#users').addClass('active');
	});
</script>

<% provide(:title, 'Users') %>

<div class="content">
  <div id="success-msg"></div>
  <%= render 'all' %>
  <%= render 'form_edit' %>
</div>

app/views/users/new.html.erb
<div id="newUser" class="content">
	<div id="error-msg" class="text-center"></div>
	<%= render 'form_new' %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<script type="text/javascript">
	$(document).ready(function() {
		$('#user-page').addClass('active');
	});
</script>

<div id="user" class="content">
	<h1 class="text-center">Пользователь <%= @user.id %></h1>
	<div class="row">
		<%= label_tag(:name, "Имя", :class => "col-sm-2 control-label text-right") %>
        <span id="name" class="col-sm-10 text-left"><%= @user.name %></span>
	</div>

	<% if @user.employee %>
	<div class="row">
		<%= label_tag(:name, "Сотрудник", :class => "col-sm-2 control-label text-right") %>
        <span id="employee" class="col-sm-10 text-left"><%= @user.employee.name %></span>
	</div>
	<% end %>

	<div class="text-center">
		<%= link_to "Редактировать", edit_user_path(@user), :class => "btn btn-primary" %>
		<%= link_to "Выйти", signout_path, method: "delete", :class => "btn btn-primary" %>
	</div>
</div>