config/routes.rb
NewVend::Application.routes.draw do
  get "machines/new"
  get 'request_tasks/count' => 'request_tasks#count'
  get 'requests/count' => 'requests#count'
  get 'mobile' => 'application#mobile', :as => :mobile

  resources :machines, only: [:index, :show, :create, :new]
  resources :users, only: [:show, :edit, :update, :new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :requests, only: [:index, :destroy, :create, :update, :edit, :show]
  resources :messages, only: [:index, :destroy, :create, :update, :edit]
  resources :request_tasks, only: [:index, :edit, :update, :show]
  resources :tasks, only: [:index, :create, :destroy, :update]
  resources :employees, only: [:index, :create, :destroy, :edit, :update]
  resources :message_tasks, only: [:index]
  resources :attributes, only: [:index, :create, :destroy, :update]
  resources :request_types, only: [:index, :create, :destroy, :update, :show]
  resources :new_vend_settings, only: [:index, :show, :update]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get 'to_assign_count' => 'request_tasks#to_assign_count', :as => :to_assign_count
  get 'to_audit_count' => 'request_tasks#to_audit_count', :as => :to_audit_count
  get 'to_execute_count' => 'request_tasks#to_execute_count', :as => :to_execute_count
  get 'to_read_assign_count' => 'request_tasks#to_read_assign_count', :as => :to_read_assign_count
  get 'to_read_execute_count' => 'request_tasks#to_read_execute_count', :as => :to_read_execute_count
  get 'to_read_by_executor_count' => 'request_tasks#to_read_by_executor_count', :as => :to_read_by_executor_count
  get 'to_read_by_assigner_count' => 'request_tasks#to_read_by_assigner_count', :as => :to_read_by_assigner_count
  get 'to_read_by_auditor_count' => 'request_tasks#to_read_by_auditor_count', :as => :to_read_by_auditor_count
  get 'to_read_by_employee_count' => 'request_tasks#to_read_by_employee_count', :as => :to_read_by_employee_count
  get 'read_request_task' => 'request_tasks#read', :as => :read_request_task
  get 'current_employee' => 'employees#current_employee', :as => :current_employee

end

app/models/machine.rb
class Machine < ActiveRecord::Base
	belongs_to :sales_location
	belongs_to :model

	has_many :requests, dependent: :destroy

	require 'open-uri'

	def self.loadMachines
		machines_json = JSON.parse(open("http://lifehack.ru/machines.json").read.force_encoding("Windows-1251").encode("UTF-8"))
		machines_info = machines_json["Machines"]
		machines_info.each { |machine|
			current = Machine.where(:guid => machine["UID"]).first
			if current
				current.update(:name => machine["Name"],
					           :location => machine["Location"])
			else
				Machine.create(:guid => machine["UID"], 
					           :name => machine["Name"],
					           :location => machine["Location"])
			end
		}

		#machines = Machine.all
		#machines.each { |machine|
		#	if !(machines_info.detect { |m| m["UID"] == machine.uid })
		#		machine.destroy
		#	end
		#}
	end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show]
  before_action :signed_in_user

  respond_to :html, :json

  # GET /machines
  # GET /machines.json 
  def index
    @machines = Machine.order("name ASC").all

    respond_with @machines
  end

  def new
    @machine = Machine.new
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  def create
    @machine = Machine.new(request_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render json: @machine, status: :created, location: @machine }
      else
        format.html { render action: 'new' }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  def signed_in_user
    redirect_to signin_url, notice: "Пожалуйста, войдите в систему" unless signed_in?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:machine).permit(:uid, :name, :location, :machine_type)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_all.html.erb
<div class="standart-table-container">
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Номер</th>
      <th>guid</th>
      <th>Имя</th>
      <th>Расположение</th>
    </tr>
    <tr>
      <th>Фильтр:</th>
      <th><input class="form-control input-sm" type="text"></th>
      <th><input class="form-control input-sm" type="text"></th>
      <th><input class="form-control input-sm" type="text"></th>
    </tr>
  </thead>

  <tbody id ="machines">
    <% @machines.each do |machine| %>
      <tr id="<%= machine.id %>">
        <td><%= link_to machine.id, machine_path(machine) %></td>
        <td><%= link_to machine.guid, machine_path(machine) %></td>
        <td><%= link_to machine.name, machine_path(machine) %></td>
        <td><%= link_to machine.location, machine_path(machine) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/machines/index.html.erb
<% provide(:title, 'Machines') %>

<script type="text/javascript">
	$(document).ready(function() {
		$('li#machines').addClass('active');
	});
</script>

<div class="content">
	<h1>Автоматы</h1>
	  <%= render 'all' %>
</div>

app/views/machines/new.html.erb
  <%= form_for(@machine) do |f| %>
    <div>
      <%= f.label :uid, "uid" %><br>
      <%= f.text_field :uid %>
    </div>
    <div>
      <%= f.label :name, "name" %><br>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :location, "location" %><br>
      <%= f.text_field :location %>
    </div>
    <div>
      <%= f.label :machine_type, "machine_type" %><br>
      <%= f.text_field :machine_type %>
    </div>
    <%= f.submit "Подтвердить", class: "btn btn-large" %>
  <% end %>  

app/views/machines/show.html.erb
<div class="content">
  <h1>Автомат <%= @machine.name %></h1>
  <hr>
  <br>
  uid: <%= @machine.uid %> <br>
  Расположение: <%= @machine.location %> <br>
  Тип: <%= @machine.machine_type %> <br>
</div>